### ISSUE TITLE
Unmet need for family planning should accept decimal numbers R12

### ISSUE THREAD

**Issue by region12** [ppmpme/issues-only#9]

**Comment by aratpineda** [comment]
experiencing the same issue
![image](https://user-images.githubusercontent.com/45053035/48881141-aea97100-ee4e-11e8-8b2d-c724f10acf2e.png)

**Comment by mjsolidarios** [comment]
I'll be able to fix the remaining issues this weekend po. Thank you for the report.

**Comment by aratpineda** [comment]
si saan na po malalaman username and password namin ayaw nmn tangapin ncr@popcom.gov.ph


Thank you and regards,

Arabella T. Pineda
Project Evaluation Officer I 
Commission on PopulationRegion NCR2F PopCom Bldg.,Welfareville Compound, Acacia Lane, Barangay Addition Hills, Mandaluyong CityT/F: 531- 6650website: http://ncr.popcom.gov.ph/facebook: https://www.facebook.com/CommissiononPopulationNationalCapitalRegion
Empowering Filipino Families POPCOM
 

    On Monday, March 25, 2019, 4:27:25 PM PDT, Mark Joseph Solidarios <notifications@github.com> wrote:  
 
 This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 
Closed #9.

**Comment by aratpineda** [comment]
Sir tagal n ganito pag ng log in ako

ncrpopcom@yahoo.com1q2w3e4r5t6y
Thank you and regards,

Arabella T. Pineda
Project Evaluation Officer I 
Commission on PopulationRegion NCR2F PopCom Bldg.,Welfareville Compound, Acacia Lane, Barangay Addition Hills, Mandaluyong CityT/F: 531- 6650website: http://ncr.popcom.gov.ph/facebook: https://www.facebook.com/CommissiononPopulationNationalCapitalRegion
Empowering Filipino Families POPCOM
 

    On Tuesday, April 2, 2019, 07:12:12 PM PDT, Arabella Pineda <aratpineda@yahoo.com> wrote:  
 
 si saan na po malalaman username and password namin ayaw nmn tangapin ncr@popcom.gov.ph


Thank you and regards,

Arabella T. Pineda
Project Evaluation Officer I 
Commission on PopulationRegion NCR2F PopCom Bldg.,Welfareville Compound, Acacia Lane, Barangay Addition Hills, Mandaluyong CityT/F: 531- 6650website: http://ncr.popcom.gov.ph/facebook: https://www.facebook.com/CommissiononPopulationNationalCapitalRegion
Empowering Filipino Families POPCOM
 

    On Monday, March 25, 2019, 4:27:25 PM PDT, Mark Joseph Solidarios <notifications@github.com> wrote:  
 
 This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 
Closed #9.

**Comment by mjsolidarios** [comment]
Ma'am Arabella,

Good day, Ma'am. Thank you for the report! The issue is now resolved. The
user details for NCR was accidentally deleted, no need to worry though -
data entries for NCR were not affected.

Sincerely,

Mark Joseph J. Solidarios
Part-time Instructor, WVSU
App Developer

**Comment by aratpineda** [comment]
Thanks 



Thank you and regards,

Arabella T. Pineda
Project Evaluation Officer I 
Commission on PopulationRegion NCR2F PopCom Bldg.,Welfareville Compound, Acacia Lane, Barangay Addition Hills, Mandaluyong CityT/F: 531- 6650website: http://ncr.popcom.gov.ph/facebook: https://www.facebook.com/CommissiononPopulationNationalCapitalRegion
Empowering Filipino Families POPCOM
 

    On Friday, November 8, 2019, 06:54:55 AM PST, Mark Joseph Solidarios <notifications@github.com> wrote:  
 
 This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 Ma'am Arabella,

Good day, Ma'am. Thank you for the report! The issue is now resolved. The
user details for NCR was accidentally deleted, no need to worry though -
data entries for NCR were not affected.

Sincerely,

Mark Joseph J. Solidarios
Part-time Instructor, WVSU
App Developer

**Comment by aratpineda** [comment]
Hi Sir Mark 
I cannot access the system. We were also surprised to find out that there is a new link for this system which is now https://me-ppmp-prod.netlify.com/dashboard/ ..Hope my encoded data in the previous link will be saved and captured in this new link. 
username: ncrpopcom@yahoo.com 1q2w3e4r5t6y

Thank you and regards,

Arabella T. Pineda
Project Evaluation Officer I 
Commission on PopulationRegion NCR2F PopCom Bldg.,Welfareville Compound, Acacia Lane, Barangay Addition Hills, Mandaluyong CityT/F: 531- 6650website: http://ncr.popcom.gov.ph/facebook: https://www.facebook.com/CommissiononPopulationNationalCapitalRegion
Empowering Filipino Families POPCOM
 

    On Friday, November 8, 2019, 06:54:55 AM PST, Mark Joseph Solidarios <notifications@github.com> wrote:  
 
 This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 Ma'am Arabella,

Good day, Ma'am. Thank you for the report! The issue is now resolved. The
user details for NCR was accidentally deleted, no need to worry though -
data entries for NCR were not affected.

Sincerely,

Mark Joseph J. Solidarios
Part-time Instructor, WVSU
App Developer

**Comment by mjsolidarios** [comment]
Good PM Ma'am. I was surprised as well that you were not informed about the
new link since I already given all the details a few months ago during the
turnover. No worries po Ma'am about the data. They have the same database
po. Were you using the new link now po? That's why you can't access?

**Comment by aratpineda** [comment]
Yes po..we had a meeting this afternoon with Ivan and Mam Tess. sir Mike...System test run nth time.


Sent from Yahoo Mail on Android 
 
  On Mon, Dec 2, 2019 at 3:43 PM, Mark Joseph Solidarios<notifications@github.com> wrote:   This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 Good PM Ma'am. I was surprised as well that you were not informed about the
new link since I already given all the details a few months ago during the
turnover. No worries po Ma'am about the data. They have the same database
po. Were you using the new link now po? That's why you can't access?

**Comment by mjsolidarios** [comment]
Good AM po Ma'am. I found the issue po. Hindi pa po kasi na approve nina
Sir Mike yung latest patch. I already informed them last November 4 pa po.
[image: patch.png]

As you may notice po we have now two versions. I'm waiting for their go
signal to apply v4.6.2rc
[image: latest-fix.png]
[image: existing-system.png]

If you check po Ma'am, you can login with 4.6.2rc
[image: login.png]

**Comment by mjsolidarios** [comment]
Just reminded them through email Ma'am. Will message you asap when the
updates are approved by Sir Mike's team. Thank you for the issue report.
